version: "3.9"
services:
  frontend:
    build:
      context: ./app
      args:
        BASE_URL: "http://localhost:3000"
    restart: always
    networks:
      - hackathon-network
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./server
    restart: always
    networks:
      - hackathon-network
    ports:
      - "3000:3000"

networks:
  hackathon-network:
    driver: bridge
