name: CI/CD - Develop (Preview)

on:
  push:
    branches:
      - develop

jobs:
  release-beta:
    name: Gerar Release Beta
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout do Código para Release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js para Release
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar Dependências do Projeto para Release
        working-directory: ./app
        run: npm ci

      - name: Executar Testes
        run: cd app && npm run test:coverage

      - name: Build do Projeto
        working-directory: ./app
        run: npm run build

      - name: Instalar Semantic Release
        working-directory: ./app
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm

      - name: Executar Semantic Release Preview
        working-directory: ./app
        run: |
          npx semantic-release
          mv CHANGELOG.md ../
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GIT_TOKEN }}
          NODE_ENV: development
